contacts:
  name: Joon Yoo
  email: joonhyoo12@gmail.com
  address: Sydney, Australia
  linkedin:
    url: https://www.linkedin.com/in/joonhyoo/
    displayText: joonhyoo
  github:
    url: https://github.com/joonhyoo/
    displayText: "@joonhyoo"
  # website:
  #   url: https://joonhyoo.dev
  #   displayText: joonhyoo.dev

position: Graduate Software Engineer

projects:
  - title: "Confluence/Rovo: Answer Your Questions"
    tech: React, Javascript, CSS, Git, Jira
    description:
      - Designed and implemented the FAQ macro component using Figma and React.
      - Implemented an auto-escalation email feature, using the SendGrid API in vanilla Javascript.
      - Reviewed and approved ~20% of pull requests by team members.
      - Monitored progress and proactively addressed code quality/stability concerns in meetings.
      - Participated in weekly stand-ups and adhered to Agile methodologies.
      - Presented live technical demos for the client and incorporated feedback into following iterations.
  - title: Shuu - Visual Habit Tracker (WIP)
    tech: React, TailwindCSS, SupaBase, Git
    description:
      - Designed a normalised relational database schema in PostGreSQL (via SupaBase).
      - Implemented CRUD functionality through SQL queries.
      - Integrated SupaBase backend services to handle SSO and authentication.
  - title: "BearGuide"
    tech: React Native, Balsamiq, Figma, Git
    description:
      - Designed and implemented User Profile and User Favourites frames.
      - Edited the product intro video and recieved a perfect grade.
      - Conducted 40% of the usability tests to iterate the design around a user-centered design approach.

education:
  - place:
      name: University of New South Wales
      link: https://www.unsw.edu.au/
    degree: B.Sc. Computer Science
    complete: Dec 2025
    location: Kensington, Australia
  - place:
      name: Keio University
      link: https://www.keio.ac.jp/en/
    complete: Aug 2025
    degree: Spring Exchange Semester
    location: Tokyo, Japan
# - place:
#     name: Osaka University - Center for International Education and Exchange
#     link: https://ciee.osaka-u.ac.jp/en/
#   degree: Winter J-Ship Program
#   complete: Feb 2025
#   location: Osaka, Japan

jobs:
  - position: Volleyball Coach
    company:
      name: Barker College
    type: Contract
    description:
      - Facilitated and ran training sessions with groups of 20+ students on a weekly basis.
      - Educated students on volleyball, and mental strategies to stay confident and positive.
    from: Oct 2024
    to: Present
    location: Sydney, Australia

  - position: Men's Co-Director
    company:
      name: Lynx Volleyball Club
    type: Volunteer
    description:
      - Helped to keep the club running.
    from: Mar 2024
    to: Dec 2025
    location: Sydney, Australia

other:
  - name: Hobbies
    items:
      - Competitive sports - Basketball & Volleyball
      - Language learning - JLPT N2 (2026)
